name: writeapaper
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: documenti 
      FILE: main.tex 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        #run: latexmk -pdf -bibtex ${{ env.FILE }}
        run: pdflatex ${{ env.FILE }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
