on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: list docuents 
        run: ls -a
      - name: Run a shell script
        run: sh ./my-script.sh
      - name: Run a javascript script 
        run: node other-script.js
